/**
 * One-off generator for lib/geo/world.ts — the vendored world outline behind the
 * admin adoption map. Keeps the runtime dependency-free: this script pre-projects
 * Natural Earth 110m country polygons to SVG path strings on a fixed equirect-
 * angular viewBox, and commits the result as plain data. No map/topojson library
 * ships to the client.
 *
 * Source: Natural Earth 1:110m Admin 0 Countries (public domain).
 *   https://github.com/nvkelso/natural-earth-vector  (geojson/ne_110m_admin_0_countries.geojson)
 *
 * Run:  npx tsx scripts/generate-world-map.ts path/to/ne_110m_admin_0_countries.geojson
 * Re-run only when refreshing the outline; the generated lib/geo/world.ts is the
 * checked-in source of truth.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const W = 1000
const H = 500

// Equirectangular projection to the fixed viewBox.
function project(lng: number, lat: number): [number, number] {
  const x = ((lng + 180) / 360) * W
  const y = ((90 - lat) / 180) * H
  return [Math.round(x * 10) / 10, Math.round(y * 10) / 10]
}

function ringPath(ring: number[][]): string {
  let d = ''
  for (let i = 0; i < ring.length; i++) {
    const [lng, lat] = ring[i]
    const [x, y] = project(lng, lat)
    d += `${i === 0 ? 'M' : 'L'}${x} ${y}`
  }
  return d + 'Z'
}

function geometryPath(geom: { type: string; coordinates: unknown }): string {
  if (geom.type === 'Polygon') {
    const polys = geom.coordinates as number[][][]
    return polys.map(ringPath).join('')
  }
  if (geom.type === 'MultiPolygon') {
    const multi = geom.coordinates as number[][][][]
    return multi.map((poly) => poly.map(ringPath).join('')).join('')
  }
  return ''
}

const src = process.argv[2]
if (!src) {
  console.error('usage: tsx scripts/generate-world-map.ts <ne_110m_admin_0_countries.geojson>')
  process.exit(1)
}

const geo = JSON.parse(readFileSync(src, 'utf8')) as {
  features: Array<{ properties: Record<string, unknown>; geometry: { type: string; coordinates: unknown } }>
}

interface Country {
  id: string
  name: string
  d: string
}

const countries: Country[] = []
for (const f of geo.features) {
  const p = f.properties
  // Natural Earth marks some sovereigns (France, Norway, …) as ISO_A2 '-99';
  // ISO_A2_EH carries the de-facto code in those cases.
  let iso = String(p.ISO_A2 ?? '')
  if (iso === '-99' || iso === '') iso = String(p.ISO_A2_EH ?? '')
  if (iso === '-99' || iso === '') continue // unmappable entity, skip
  const name = String(p.NAME ?? p.NAME_LONG ?? iso)
  const d = geometryPath(f.geometry)
  if (d) countries.push({ id: iso, name, d })
}

countries.sort((a, b) => a.id.localeCompare(b.id))

const header = `// GENERATED by scripts/generate-world-map.ts — do not edit by hand.
// Vendored world outline for the admin adoption map: Natural Earth 1:110m Admin 0
// Countries (PUBLIC DOMAIN, https://www.naturalearthdata.com/about/terms-of-use/),
// pre-projected (equirectangular) to a ${W}x${H} viewBox so no map/topojson
// library ships at runtime. \`d\` is an SVG path; \`id\` is the ISO 3166-1 alpha-2
// code Vercel's edge headers emit, so adoption rows join straight onto it.

export const WORLD_W = ${W}
export const WORLD_H = ${H}

export interface WorldCountry {
  /** ISO 3166-1 alpha-2 */
  id: string
  name: string
  /** SVG path on the WORLD_W x WORLD_H viewBox */
  d: string
}

/** Project a coordinate onto the same viewBox the country paths use. */
export function projectToWorld(lng: number, lat: number): { x: number; y: number } {
  return { x: ((lng + 180) / 360) * WORLD_W, y: ((90 - lat) / 180) * WORLD_H }
}

export const WORLD_COUNTRIES: WorldCountry[] = ${JSON.stringify(countries)}
`

writeFileSync('lib/geo/world.ts', header)
console.error(`wrote lib/geo/world.ts — ${countries.length} countries, ${(header.length / 1024).toFixed(0)}KB`)
